Repository hmcts/rd-commondata-dataload, pull requests merged in 2021-12, with the labels that each got.

#6 Feat:Create new table and insert data for Flag Details
  Dockerfile
  build.gradle
  charts/rd-commondata-dataload/Chart.yaml
  charts/rd-commondata-dataload/values.preview.template.yaml
  charts/rd-commondata-dataload/values.yaml
  config/owasp/suppressions.xml
  database/Dockerfile
  database/init-db.sh
  docker-compose.yml
  src/main/java/uk/gov/hmcts/reform/rd/commondata/RdCommondataLoadApplication.java
  src/main/resources/application.yaml
  src/main/resources/db/migration/V1_1__init_tables.sql
  src/main/resources/db/migration/V1_2__init_table_flag_details.sql
Labels: ns:rd, rel:rd-commondata-dataload-pr-6, prd:rd

#13 RDCC-3636:Changes made to sync master build with demo,ithc and perftest
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-13

#14 fix: RDCC-3773 patch log4j to the latest version
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-14

#7 RDCC-3713: Create a new table for Hearing Channel
  src/main/resources/db/migration/V1_3__insert_hearing_channel.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-7

#24 Feat:Create a new View for LOV
  src/main/resources/db/migration/V1_4__create_view_mv_list_of_values .sql
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-24

#27 fix: patch log4j to the 2.16.0 in all applications to fix CVE-2021-45046
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-27

#31 fix: CVE-2021-45105 by upgrading log4j to 2.17.0
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-31
