Repository hmcts/rd-commondata-dataload, pull requests merged in 2022-12, with the labels that each got.

#200 CVE-2021-37533 Issue Suppression : RDCC - 6007
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-200

#201 Fixed the functional test cases
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataApplicationExceptionAndAuditTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataApplicationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataCaseLinkingLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataCategoriesLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFileStatusCheckTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFlagDetailsLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFlagServiceLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/testsupport/CommonDataFunctionalBaseTest.java
  src/functionalTest/resources/application-functional.yml
  src/functionalTest/resources/sourceFiles/flagDetails/flag_details.csv
  src/functionalTest/resources/sourceFiles/flagDetails/flag_details_failure.csv
  src/functionalTest/resources/sourceFiles/flagDetails/flag_details_success_with_quotes.csv
  src/functionalTest/resources/testData/commondata_insert_flag_details.sql
  src/functionalTest/resources/testData/commondata_truncate.sql
  src/functionalTest/resources/testData/commondata_truncate_flag_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-201

#203 RDCC-6061: Adding Suppression for `CVE-2022-41881`
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-203

#204 RDCC-6073: Fix for `CVE-2022-41915`
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-204
