Repository hmcts/rd-commondata-dataload, pull requests merged in 2022-05, with the labels that each got.

#101 RDCC-4648: Increasing `CVE-2020-23171` Suppression Date
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-101

#102 fix: RDCC-4670 Fixed CVE-2022-24823 by upgrading netty
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-102

#103 RDCC-4690: Suppressing CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-103

#106 Bumped spring dependencies version to 5.3.20
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-106

#97 Added for processing new file 'CaseLinkingReasons.csv'
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataCaseLinkingLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/testsupport/CommonDataFunctionalBaseTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/config/CommonDataCamelConfig.java
  src/functionalTest/resources/application-functional.yml
  src/functionalTest/resources/sourceFiles/caseLinking/case_linking_failure_additional_header.csv
  src/functionalTest/resources/sourceFiles/caseLinking/case_linking_failure_unknown_header.csv
  src/functionalTest/resources/sourceFiles/caseLinking/case_linking_partial_success_categoryKey_numeric.csv
  src/functionalTest/resources/sourceFiles/caseLinking/case_linking_success.csv
  src/functionalTest/resources/sourceFiles/caseLinking/case_linking_success_insensitive_headers.csv
  src/functionalTest/resources/sourceFiles/caseLinking/case_linking_success_leadingspace.csv
  src/functionalTest/resources/sourceFiles/caseLinking/case_linking_success_with_quotes.csv
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/task/CommonDataCaseLinkingRouteTask.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/configuration/BatchConfig.java
  src/main/resources/application-camel-routes-common.yaml
  src/main/resources/application-crd-case-linking-reasons-router.yaml
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/task/CommonDataCaseLinkingRouteTaskTest.java
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-97

#108 Nightly build failed due to mutation test coverage for new class
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-108

#109 Commondata:correct the date format in flag details table of common reference data
  src/main/resources/db/migration/V1_8__Insert_table_flag_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-109
