Repository hmcts/rd-commondata-dataload, pull requests merged in 2022-11, with the labels that each got.

#182 RDCC-5778: Upgrading `tomcat` to version `9.0.68`
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-182

#186 RDCC-5853: enabling Fortify Scan
  Jenkinsfile_nightly
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-186

#187 RDCC-5853: Fix - Syncing Fortify Config with PRD
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-187

#185 Case Flags : Add two new columns in Flag Service table : RDCC 5571
  src/functionalTest/resources/dbmigration/V1_11__alter_flag_service_details.sql
  src/main/resources/db/migration/V1_11__alter_flag_service_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-185

#189 Revert "Case Flags : Add two new columns in Flag Service table : RDCC 5571"
  src/functionalTest/resources/dbmigration/V1_11__alter_flag_service_details.sql
  src/main/resources/db/migration/V1_11__alter_flag_service_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-189

#190 Revert "Revert "Case Flags : Add two new columns in Flag Service table : RDCC 5571""
  src/functionalTest/resources/dbmigration/V1_11__alter_flag_service_details.sql
  src/main/resources/db/migration/V1_11__alter_flag_service_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-190

#191 RDCC-5741 (sync the flyway with api project)
  src/functionalTest/resources/dbmigration/V1_12__update_table_flag_details.sql
  src/functionalTest/resources/dbmigration/V1_2__create_view_mv_list_of_values .sql
  src/functionalTest/resources/dbmigration/V1_4__create_table_List_Of_Values.sql
  src/functionalTest/resources/dbmigration/V1_6__Alter_List_Of_Values.sql
  src/functionalTest/resources/dbmigration/V1_8__Insert_table_flag_details.sql
  src/functionalTest/resources/dbmigration/V1_9__Insert_table_flag_details.sql
  src/main/resources/db/migration/V1_12__update_table_flag_details.sql
  src/main/resources/db/migration/V1_4__create_table_List_Of_Values.sql
  src/main/resources/db/migration/V1_6__Alter_List_Of_Values.sql
  src/main/resources/db/migration/V1_8__Insert_table_flag_details.sql
  src/main/resources/db/migration/V1_9__Insert_table_flag_details.sql
  src/main/resources/db/migration/V2_0__Insert_table_flag_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-191

#192 Upgrade Terraform version 1.3.X :: RDCC-5894
  charts/rd-commondata-dataload/Chart.yaml
  infrastructure/.terraform-version
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-192

#196 RDCC-5914 -Refresh Flag Details
  src/functionalTest/resources/dbmigration/V1_13__Insert_table_flag_details.sql
  src/main/resources/db/migration/V1_13__Insert_table_flag_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-196

#197 CVE Fix for Postgresql
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-197
