Repository hmcts/rd-commondata-dataload, pull requests merged in 2022-02, with the labels that each got.

#49 Update flag details table
  src/main/resources/db/migration/V1_8__insert_flag_details_and_service.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-49

#39 RDCC-3923: Common-data-load Remove Deprecated Jcenter Repository
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-39

#59 RDCC-4048: Fix CVEs
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-59

#53 fixed sonar issues
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/IFlagCodeProcessor.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/binder/FlagServiceTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/listener/JobResultListenerTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/mapper/FlagServiceMapperTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/FlagServiceProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/task/CommonDataFlagServiceRouteTaskTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/util/CommonDataExecutorTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/util/CommonDataLoadUtilsTest.java
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-53

#58 Gradle Upgrade 7.3.3
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-58

#61 fix: Removed bootstrap.yaml and modified config to retrieve the secrets
  build.gradle
  charts/rd-commondata-dataload/values.preview.template.yaml
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-61
