Repository hmcts/rd-commondata-dataload, pull requests merged in 2022-08, with the labels that each got.

#146 Feat:CommonRefData - LOV - Duplicate records errors not audited in exception table and Job status is Success
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataCategoriesLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/config/CommonDataCamelConfig.java
  src/functionalTest/resources/application-functional.yml
  src/functionalTest/resources/dbmigration/V1_6__Alter_List_Of_Values.sql
  src/functionalTest/resources/sourceFiles/categories/list_of_values_duplicate_rec_case1.csv
  src/functionalTest/resources/sourceFiles/categories/list_of_values_duplicate_rec_case2.csv
  src/functionalTest/resources/sourceFiles/categories/list_of_values_duplicate_rec_case3.csv
  src/functionalTest/resources/sourceFiles/categories/list_of_values_duplicate_rec_case4.csv
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessor.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessorTest.java
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-146

#149 Feat:Nightly build is failure for rd-commondata-dataload
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-149

#148 Feat:RDCC-5178:Changes made to sync flywayscripts
  src/functionalTest/resources/dbmigration/V1_1__init_tables.sql
  src/functionalTest/resources/dbmigration/V1_2__create_view_mv_list_of_values .sql
  src/functionalTest/resources/dbmigration/V1_3__alter_flag_details.sql
  src/functionalTest/resources/dbmigration/V1_4__create_table_List_Of_Values.sql
  src/functionalTest/resources/dbmigration/V1_5__drop_view_table_mv_list_of_values.sql
  src/functionalTest/resources/dbmigration/V1_7__Insert_table_flag_details.sql
  src/functionalTest/resources/dbmigration/V1_8__Insert_table_flag_details.sql
  src/functionalTest/resources/dbmigration/V1_9__Insert_table_flag_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-148

#151 fix for handling 'D' records
  build.gradle
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessor.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessorTest.java
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-151

#153 CVE Fix
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-153

#156 Refactor code to remove the hard coding
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-156
