Repository hmcts/rd-commondata-dataload, pull requests merged in 2022-03, with the labels that each got.

#83 CVE Fix
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-83

#85 CVE Fix for Jackson
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-85

#80 CRD: Drop existing view and tables for List Of Values
  src/main/resources/db/migration/V1_5__drop_view_table_mv_list_of_values.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-80

#86 CVE Fix for postgresql
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-86
