Repository hmcts/rd-commondata-dataload, pull requests merged in 2022-09, with the labels that each got.

#159 RDCC-5392: adding suppression for CVE-2022-25857
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-159

#157 Rdcc 5328
  src/main/resources/db/migration/V2_0__Insert_table_flag_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-157

#158 RDCC-5357 Handling 'D' records in pre-processor logic
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessor.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/util/CommonDataLoadConstants.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessorTest.java
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-158

#160 RDCC-5447: Suppress Snakeyaml CVEs
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-160

#161 RDCC-5496: excluding `jettison` to fix `CVE-2022-40149` & `CVE-2022-40150`
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-161
