Repository hmcts/rd-commondata-dataload, pull requests merged in 2022-06, with the labels that each got.

#111 Common data Add multi arch image configuration
  Dockerfile
  acb.tpl.yaml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-111

#113 Update data ingestion library version to latest - CVE Fix
  build.gradle
  charts/rd-commondata-dataload/Chart.yaml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-113

#115 config: RDCC-4823 Configured renovate
  renovate.json
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-115

#117 commmon data Load Auto merge renovate PRs
  .github/workflows/combine-prs.yml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-117

#121 RDCC-4906 CRD : Test Flag Details Changes
  src/main/resources/db/migration/V1_9__Insert_table_flag_details.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-121
