Repository hmcts/rd-commondata-dataload, pull requests merged in 2022-04, with the labels that each got.

#89 RDCC-4402: CVE Fix
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-89

#91 change unique key in to composite
  src/main/resources/application-crd-list-of-values-router.yaml
  src/main/resources/db/migration/V1_6__Alter_List_Of_Values.sql
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-91

#94 commondata-dataload-Nightly build failure
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-94

#88 Feat:Java 17 Migration for Common Reference Data
  Dockerfile
  build.gradle
  docker-compose.yml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-88
