Repository hmcts/rd-commondata-dataload, pull requests merged in 2023-05, with the labels that each got.

#239 addresses CVE-2023-20873, CVE-2023-20862
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-239

#240 Addresses CVE-2021-22044
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-240

#242 DTSRD-456: fix CVE-2023-28709
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-242
