Repository hmcts/rd-commondata-dataload, pull requests merged in 2023-03, with the labels that each got.

#220 header disable
  src/main/resources/application-crd-flag-details-router.yaml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-220

#221 Feat:Common : Add header validation to check UTF-8 file format
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataCategoriesLoadTest.java
  src/functionalTest/resources/sourceFiles/categories/list_of_values_utf8_header.csv
  src/main/resources/application-crd-list-of-values-router.yaml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-221

#222 [RDCC-6450]-changed the validation flag as true
  src/main/resources/application-crd-flag-details-router.yaml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-222

#223 Feat:Address CVEs in all Reference Data repositories - Common Reference Data
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-223

#224 [RDCC-6242]-Upgrade Libs in Data load projects
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-224

#228 RDCC-6611 - suppress CVE-2022-1471
  bin/functionalTest/sourceFiles/categories/list_of_values_utf8_header.csv
  bin/main/application-crd-list-of-values-router.yaml
  charts/rd-commondata-dataload/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-228

#231 RDCC-6682: address nightly build failure
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-231
