Repository hmcts/rd-commondata-dataload, pull requests merged in 2023-01, with the labels that each got.

#205 RDCC-6118: Adding suppression for `CVE-2021-4277`
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-205

#206 RDCC-6130: Adding suppressions for `CVE-2022-3064` & `CVE-2021-4235`
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-206

#207 RDCC-6139: Upgrading Tomcat to `9.0.69` to fix `CVE-2022-45143`
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-207

#209 RDCC-6046 [Spring Boot upgrade - Dataload project]
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataApplicationExceptionAndAuditTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataApplicationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataCategoriesLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFileStatusCheckTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFlagServiceLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/testsupport/CommonDataBlobSupport.java
  src/functionalTest/resources/application-functional.yml
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-209

#198 RDCC-5920: Common : Change the Flag Details upload into an ETL ingestion mechanism
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataApplicationExceptionAndAuditTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataApplicationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataCaseLinkingLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataCategoriesLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFileStatusCheckTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFlagDetailsLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFlagServiceLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/testsupport/CommonDataFunctionalBaseTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/config/CommonDataCamelConfig.java
  src/functionalTest/resources/application-functional.yml
  src/functionalTest/resources/dbmigration/V1_12__update_table_flag_details.sql
  src/functionalTest/resources/dbmigration/V1_13__Insert_table_flag_details.sql
  src/functionalTest/resources/dbmigration/V1_7__Insert_table_flag_details.sql
  src/functionalTest/resources/dbmigration/V1_7__alter_flag_service_details.sql
  src/functionalTest/resources/dbmigration/V1_8__Insert_table_flag_details.sql
  src/functionalTest/resources/dbmigration/V1_9__Insert_table_flag_details.sql
  src/functionalTest/resources/sourceFiles/flagDetails/flag_details.csv
  src/functionalTest/resources/sourceFiles/flagDetails/flag_details_expired_record_partial_success.csv
  src/functionalTest/resources/sourceFiles/flagDetails/flag_details_failure.csv
  src/functionalTest/resources/sourceFiles/flagDetails/flag_details_failure_unknown_header.csv
  src/functionalTest/resources/sourceFiles/flagDetails/flag_details_partial_success_missing_categoryId.csv
  src/functionalTest/resources/sourceFiles/flagDetails/flag_details_partial_success_missing_flag_code.csv
  src/functionalTest/resources/sourceFiles/flagDetails/flag_details_partial_success_missing_id.csv
  src/functionalTest/resources/sourceFiles/flagDetails/flag_details_partial_success_missing_value_en.csv
  src/functionalTest/resources/sourceFiles/flagDetails/flag_details_success.csv
  src/functionalTest/resources/sourceFiles/flagDetails/flag_details_success_insensitive_headers.csv
  src/functionalTest/resources/sourceFiles/flagDetails/flag_details_success_leadingspace.csv
  src/functionalTest/resources/sourceFiles/flagDetails/flag_details_success_with_quotes.csv
  src/functionalTest/resources/testData/commondata_truncate.sql
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/binder/FlagDetails.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/mapper/FlagDetailsMapper.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessor.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/FlagDetailsProcessor.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/FlagServiceProcessor.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/IFlagCodeProcessor.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/task/CommonDataFlagDetailsRouteTask.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/util/CommonDataLoadConstants.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/util/CommonDataLoadUtils.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/configuration/BatchConfig.java
  src/main/resources/application-camel-routes-common.yaml
  src/main/resources/application-crd-flag-details-router.yaml
  src/main/resources/application.yaml
  src/main/resources/db/migration/V1_12__update_table_flag_details.sql
  src/main/resources/db/migration/V1_13__Insert_table_flag_details.sql
  src/main/resources/db/migration/V1_7__Insert_table_flag_details.sql
  src/main/resources/db/migration/V1_7__alter_flag_service_details.sql
  src/main/resources/db/migration/V1_8__Insert_table_flag_details.sql
  src/main/resources/db/migration/V1_9__Insert_table_flag_details.sql
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/binder/FlagDetailsTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/mapper/FlagDetailsMapperTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/FlagDetailsProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/task/CommonDataFlagDetailsRouteTaskTest.java
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-198

#211 RDCC-6155: changing `header-validation-enabled` flag to `false`
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataCategoriesLoadTest.java
  src/functionalTest/resources/application-functional.yml
  src/main/resources/application-crd-list-of-values-router.yaml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-211

#210 [RDCC-6046]Upgrade of the AppInsight version
  Dockerfile
  infrastructure/.terraform-version
Labels: ns:rd, prd:rd, no-changes, rel:rd-commondata-dataload-pr-210
