Repository hmcts/rd-commondata-dataload, pull requests merged in 2023-11, with the labels that each got.

#276 Update application.yamlto add schema to connection string
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-276

#277 Update application.yaml. Reverting changes to connection string
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-277

#270 Rdcc filter d records
  charts/rd-commondata-dataload/Chart.yaml
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataCategoriesLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFileStatusCheckTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/testsupport/CommonDataFunctionalBaseTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/config/CommonDataCamelConfig.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessor.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/FlagDetailsProcessor.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/FlagServiceProcessor.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/OtherCategoriesProcessor.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/task/CommonDataCategoriesRouteTask.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/task/CommonDataOtherCategoriesRouteTask.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/util/CommonDataDRecords.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/util/CommonDataExecutor.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/util/CommonDataLoadConstants.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/configuration/BatchConfig.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/mapper/FlagDetailsMapperTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/FlagDetailsProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/OtherCategoriesProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/task/CommonDataCaseLinkingRouteTaskTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/task/CommonDataCategoriesRouteTaskTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/task/CommonDataFlagDetailsRouteTaskTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/task/CommonDataFlagServiceRouteTaskTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/task/CommonDataOtherCategoriesRouteTaskTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/util/CommonDataDRecordsTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/util/CommonDataExecutorTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/util/CommonDataLoadUtilsTest.java
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-commondata-dataload-pr-270

#280 DTSRD-1466.Updating schema parameter with hibernate
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-280

#281 Update acb.tpl.yaml
  acb.tpl.yaml
  charts/rd-commondata-dataload/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-281

#282 Suppresses CVE-2023-36052
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-282

#283 Addresses CVE-2023-35887
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-283
