Repository hmcts/rd-commondata-dataload, pull requests merged in 2023-06, with the labels that each got.

#244 removed suppressions
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-244

#249 Renovate config
  .github/renovate.json
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-249

#245 Update README.md
  README.md
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-245

#252 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-252
