Repository hmcts/rd-commondata-dataload, pull requests merged in 2023-10, with the labels that each got.

#271 DTSRD-1456
  build.gradle
  charts/rd-commondata-dataload/Chart.yaml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-271

#273 Remedy for CVEs
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-273

#275 DTSRD-1456.suppressing as no known netty handler version available wi…
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-275
