Repository hmcts/rd-commondata-dataload, pull requests merged in 2023-04, with the labels that each got.

#233 Addresses PR pipeline failure
  Jenkinsfile_CNP
  build.gradle
  charts/rd-commondata-dataload/Chart.yaml
  charts/rd-commondata-dataload/values.preview.template.yaml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-233

#225 RDCC-6528-Address_Sonar_issues
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/FlagDetailsProcessor.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/IFlagCodeProcessor.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/util/CommonDataLoadUtils.java
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-225

#234 DTSRD 82: update URLs for Preview and AAT
  Jenkinsfile_CNP
  security.sh
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-234

#235 Update to spring-boot 2.7.10
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-235

#236 Update spring-security to 5.8.2
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-236

#237 Addresses CVE-2023-20863
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-237
