Repository hmcts/rd-commondata-dataload, pull requests merged in 2023-12, with the labels that each got.

#286 Addresses CVE-2023-34055, CVE-2023-46589
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-286

#291 Addresses CVE-2023-6378
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-291

#301 Update dependencycheck to use default
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-301

#303 Fix CVE CVE-2023-48795
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-303
