Repository hmcts/rd-commondata-dataload, pull requests merged in 2024-08, with the labels that each got.

#378 Enable Pitest verbose logging
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-378

#381 Build fix - restore junit 5.9.2 and junit-platform 1.9.2
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-381

#388 disable pitest verbose logging
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-388

#394 Update build.gradle
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-394
