Repository hmcts/rd-commondata-dataload, pull requests merged in 2025-01, with the labels that each got.

#441 CME-300: Update azurerm
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, aat/no-changes, prod/no-changes, rel:rd-commondata-dataload-pr-441

#414 DTSRD-72: Spring boot upgrade
  .github/workflows/ci.yml
  Dockerfile
  acb.tpl.yaml
  bin/main/application-crd-list-of-values-router.yaml
  build.gradle
  charts/rd-commondata-dataload/values.preview.template.yaml
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataApplicationExceptionAndAuditTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataApplicationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataCaseLinkingLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataCategoriesLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFileStatusCheckTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFlagDetailsLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFlagServiceLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataOtherCategoriesLoadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/testsupport/CommonDataBlobSupport.java
  src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/config/CommonDataCamelConfig.java
  src/functionalTest/resources/application-functional.yml
  src/functionalTest/resources/dbmigration/V1_9__spring-batch-schema-recreate.sql
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/binder/Categories.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/binder/FlagDetails.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/binder/FlagService.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/binder/OtherCategories.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/util/CommonDataDRecords.java
  src/main/java/uk/gov/hmcts/reform/rd/commondata/configuration/BatchConfig.java
  src/main/resources/application-camel-routes-common.yaml
  src/main/resources/application-crd-case-linking-reasons-router.yaml
  src/main/resources/application-crd-flag-details-router.yaml
  src/main/resources/application-crd-flag-service-router.yaml
  src/main/resources/application-crd-list-of-values-router.yaml
  src/main/resources/application-crd-other-categories-router.yaml
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/binder/FlagDetailsTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/binder/FlagServiceTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/FlagDetailsProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/FlagServiceProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/OtherCategoriesProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/util/CommonDataDRecordsTest.java
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-commondata-dataload-pr-414

#442 DTSRD-4065
  build.gradle
Labels: ns:rd, prd:rd

#443 DTSRD-72: Fix nightly build
  build.gradle
Labels: ns:rd, prd:rd

#446 Update HMCTS gradle plugin to 0.12.64
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-commondata-dataload-pr-446
